name: CityWorld
main: me.daddychurchill.CityWorld.CityWorld
version: 2.01
load: startup
author: DaddyChurchill
commands:
  cityworld:
    description: Teleports you to/from the default CityWorld
    usage: /cityworld [leave] [normal|nether|the_end] [floating]
  citychunk:
    description: Performs specific maintenance on chunks of CityWorld
    usage: /citychunk regen | clean [chunkradius]
  citylines:
    description: Draws plot lines for use with WorldEdit
    usage: /citylines [chunksWide [chunksLength [floorsUp [floorsDown]]]]
  cityinfo:
    description: Describes the current chunk
    usage: /cityinfo
permissions:
  cityworld.*:
    description: Gives access to all CityWorld commands
    children:
      cityworld.command: true
      cityworld.create: true
      citychunk.command: true
      cityinfo.command: true
  cityworld.command:
    description: Allows users to enter and exit the default CityWorld
    default: op
  cityworld.create:
    description: Allows users to create the default CityWorld if it doesn't exist when the user enters it
    default: op
  citychunk.command:
    description: Allows users to regenerate or cleanup world chunks
    default: op
  citylines.command:
    description: Allows users to create plot lines for use with WorldEdit
    default: op
  cityinfo.command:
    description: Allows users to get chunk info
    default: op